# Generated by Django 5.2.5 on 2025-09-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='empresa',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='conectividade',
            field=models.BooleanField(default=False),
        ),
    ]
