# Generated by Django 5.2.5 on 2025-09-02 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('armazens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('data_inst', models.DateField()),
                ('faixa_temp', models.BooleanField(default=False)),
                ('minima', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('armazem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='armazens.armazem')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('faixa_temp', False), models.Q(('minima__isnull', False), ('maxima__isnull', False)), _connector='OR'), name='sensor_faixa_temp_requires_min_max'), models.CheckConstraint(condition=models.Q(models.Q(('maxima__isnull', True), ('minima__isnull', True)), ('minima__lte', models.F('maxima')), _connector='OR'), name='sensor_min_lte_max')],
            },
        ),
    ]
