# Generated by Django 5.2.5 on 2025-09-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='faixa_temp',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, exige valores mínima e máxima'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='id',
            field=models.CharField(help_text='Identificador único definido pelo usuário', max_length=64, primary_key=True, serialize=False),
        ),
    ]
