# Generated by Django 5.2.5 on 2025-09-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0002_alter_sensor_faixa_temp_alter_sensor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='instalador_id',
            field=models.CharField(blank=True, help_text='ID do instalador enviado pelo front', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='data_inst',
            field=models.DateField(help_text='Data de instalação do sensor'),
        ),
    ]
