# Generated by Django 5.2.5 on 2025-09-04 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armazens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armazem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='armazem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='armazem',
            name='data_instalacao',
            field=models.DateField(default=datetime.date(2025, 9, 4), verbose_name='Data de instalação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='armazem',
            name='instalador',
            field=models.CharField(default='Desconhecido', max_length=120, verbose_name='Instalador'),
            preserve_default=False,
        ),
    ]
